
/* <===== Creación tabla eeff_datos=====> */

CREATE TABLE eeff_datos(
id SERIAL,
Trimestre INT DEFAULT NULL,
Rut INT DEFAULT NULL,
Razon_Social VARCHAR(300) DEFAULT NULL,
Dato VARCHAR(2) DEFAULT NULL,
UM VARCHAR(6) DEFAULT NULL,
Cuentas_IFRS VARCHAR(400) DEFAULT NULL,
Monto numeric DEFAULT NULL,
Taxonomia VARCHAR(20) DEFAULT NULL,
Tipo_de_Informe VARCHAR(20) DEFAULT NULL

PRIMARY KEY (id),
FOREIGN KEY (Cuentas_IFRS) REFERENCES cuentas(Cuentas_IFRS),
FOREIGN KEY (Rut) REFERENCES Empresas_SA(Rut_SA)
)

